apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: visitors-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: VisitorsApp is the Schema for the visitorsapps API
      displayName: Visitors App
      kind: VisitorsApp
      name: visitorsapps.app.jxlwqq.github.io
      version: v1alpha1
  description: visitors-operator
  displayName: visitors-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - visitors-operator
  links:
  - name: Visitors Operator
    url: https://visitors-operator.domain
  maintainers:
  - email: jxlwqq@gmail.com
    name: jxlwqq
  maturity: alpha
  provider:
    name: jxlwqq
    url: github.com/jxlwqq
  version: 0.0.0
